//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuildCars.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Car()
        {
            this.Customers = new HashSet<Customer>();
            this.Purchases = new HashSet<Purchase>();
        }
    
        public int CarId { get; set; }
        public int Year { get; set; }
        public int CarMakeId { get; set; }
        public int CarModelId { get; set; }
        public int TypeId { get; set; }
        public int BodyStyleId { get; set; }
        public int TransmissionId { get; set; }
        public int ColorId { get; set; }
        public int InteriorId { get; set; }
        public decimal Mileage { get; set; }
        public string VINnumber { get; set; }
        public decimal SalePrice { get; set; }
        public decimal MSRP { get; set; }
        public string CarDescription { get; set; }
        public string ImageFileName { get; set; }
        public Nullable<bool> IsFeatured { get; set; }
        public Nullable<bool> IsPurchased { get; set; }
    
        public virtual BodyStyle BodyStyle { get; set; }
        public virtual CarMake CarMake { get; set; }
        public virtual CarModel CarModel { get; set; }
        public virtual Color Color { get; set; }
        public virtual Interior Interior { get; set; }
        public virtual Transmission Transmission { get; set; }
        public virtual CarType CarType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer> Customers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchase> Purchases { get; set; }
    }
}
