//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuildCars.Data
{
    using System;
    
    public partial class Featured
    {
        public int CarId { get; set; }
        public int Year { get; set; }
        public Nullable<int> CarMakeId { get; set; }
        public string MakeName { get; set; }
        public Nullable<int> CarModelId { get; set; }
        public string ModelName { get; set; }
        public int ColorId { get; set; }
        public int InteriorId { get; set; }
        public decimal Mileage { get; set; }
        public decimal MSRP { get; set; }
        public decimal SalePrice { get; set; }
        public string VINnumber { get; set; }
        public string ImageFileName { get; set; }
        public Nullable<bool> IsFeatured { get; set; }
    }
}
